

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: attractus_dev_db
  username: attractus

test:
    <<: *default
    database: attractus_test_db
    username: attractus

production:
    <<: *default
    database: attractus_db
